.Dd $Mdocdate: July 17 2018 $
.Dt DRIST 1
.Os
.Sh NAME
.Nm drist
.Nd dumb remote installer shell tool, a remote deployment tool
.Sh SYNOPSIS
.Nm 
.Ar server
.Sh DESCRIPTION

.Nm
is a tool to configure remote servers using
.Xr ssh 1 
and
.Xr rsync 1 .
.Nm
has been designed to be simple, so it may not offer all the features
you want.

When you run
.Nm Ns
, it will look at a set of special directories in the current working
directory.

Here is the whole sequence, with
.Em HOSTNAME
being the result of
.Ql uname -n
on the remote system:

.Bl -enum -offset indent -compact
.It
if folder
.Ar files
exists, its content is copied to
.Ar server
.It
if folder
.Ar files- Ns Em HOSTNAME
exists, its content copied to
.Ar server
.It
if folder
.Ar absent
exists, filenames in it are removed from
.Ar server
.It
if folder
.Ar absent- Ns Em HOSTNAME
exists, filenames in it are removed from
.Ar server
.It
if file
.Ar script
exists, it is executed remotely on
.Ar server
.It
if file
.Ar script- Ns Em HOSTNAME
exists, it is executed remotely on
.Ar server
.El

The presence of each of those files or directories is optional.

If the directory
.Ar files
is present, its content will be copied to the remote
.Ar server
relatively to the root / directory. You can create
.Ar files- Ns Em HOSTNAME
with
.Em HOSTNAME
being the result of the command
.Ql uname -n
on the remote server. The content of this folder will be copied to the
remote server after the
.Ar files
directory has been processed. This folder is useful for adding
.Em HOSTNAME Ns -specific
files.

After the files are copied,
.Nm
will look at two the folders
.Ar absent
and
.Ar absent Ns Em HOSTNAME
in the current working directory.
.Nm
will remotely delete all files listed in this directory tree.

Finally, the file
.Ar script
be copied to the remote server, executed and deleted (shall the script
succeed or not). If
.Ar script- Ns Em HOSTNAME
exists, it will be processed in the same way. This is useful if you
need to run
.Em HOSTNAME Ns -specific
commands.

I recommend writing small "modules" which would install the required
packages for a task and provide the files needed, rather than writing a
full-blown module for deploying an entire system at once.

.Nm 
does not handle file permissions and ownership. Thoses should be
modified by the
.Ar script
file.
.
.Sh EXAMPLES
Please see the
.Ar examples
directory in the
.Nm
distribution.

.Sh EXIT 
.Ex -std drist
.Sh SEE ALSO
.Xr rsync 1
.Sh Authors
.An -nosplit
The
.Nm
program was written by
.An Solène Rapenne Aq Mt solene@perso.pw
